name: absensi_bapenda
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  get: 4.6.5
  flutter_screenutil: 5.8.2
  shared_preferences: 2.1.1
  dio: 5.1.2
  google_fonts: 4.0.5
  convex_bottom_bar: 3.2.0
  geocoding: 2.1.0
  geolocator: 9.0.2
  intl: 0.18.1
  image_picker: 0.8.7+5
  flutter_image_compress: 2.0.3
  path_provider: 2.0.15
  restart_app: 1.2.1
  url_launcher: 6.1.11
  permission_handler: 10.4.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  image_path: assets/images/app_logo/play_store_512.png
  android: true
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

